name: Spikhouse CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Audit
        run: npm audit --production

  test-unit:
    needs: [audit]

    strategy:
      matrix:
        app: [api, client]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get install lsb-core

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint ${{matrix.app}}

      - name: Test
        run: npm test ${{matrix.app}} --runInBand --testTimeout=30000
        env:
          MONGOMS_DEBUG: 1

  test-e2e:
    needs: [audit]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint client-e2e

      - name: Start database
        run: docker run -p 27017:27017 --name mongo -d mongo:4

      - name: Wait for DB to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Test
        run: npm run nx serve api & npm run e2e

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: dist/cypress/apps/client-e2e/screenshots
          retention-days: 1

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: dist/cypress/apps/client-e2e/videos
          retention-days: 1

  # TODO: Docker steps & deployment
